import type { Game } from "./games";

export const talha37Games: Game[] = [
  {
    slug: "talha37-01-candy-crush-game",
    title: "Candy Crush Game",
    coverImage: "/covers/talha37-01-candy-crush-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Candy Crush Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Puzzle", "Casual", "Score Attack"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-01-candy-crush-game/index.html",
  },
  {
    slug: "talha37-02-pac-man-game",
    title: "Pac Man Game",
    coverImage: "/covers/talha37-02-pac-man-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Pac Man Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-02-pac-man-game/index.html",
  },
  {
    slug: "talha37-03-chess-game",
    title: "Chess Game",
    coverImage: "/covers/talha37-03-chess-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Chess Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Board", "Logic", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-03-chess-game/index.html",
  },
  {
    slug: "talha37-04-doodle-jump-game",
    title: "Doodle Jump Game",
    coverImage: "/covers/talha37-04-doodle-jump-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Doodle Jump Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-04-doodle-jump-game/index.html",
  },
  {
    slug: "talha37-05-solitaire-game",
    title: "Solitaire Game",
    coverImage: "/covers/talha37-05-solitaire-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Solitaire Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-05-solitaire-game/index.html",
  },
  {
    slug: "talha37-06-sudoku-game",
    title: "Sudoku Game",
    coverImage: "/covers/talha37-06-sudoku-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Sudoku Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Numbers", "Logic", "Grid"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-06-sudoku-game/index.html",
  },
  {
    slug: "talha37-07-crossy-road-game",
    title: "Crossy Road Game",
    coverImage: "/covers/talha37-07-crossy-road-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Crossy Road Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-07-crossy-road-game/index.html",
  },
  {
    slug: "talha37-08-rock-paper-scissors",
    title: "Rock Paper Scissors",
    coverImage: "/covers/talha37-08-rock-paper-scissors.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Rock Paper Scissors implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-08-rock-paper-scissors/index.html",
  },
  {
    slug: "talha37-09-flappy-bird-game",
    title: "Flappy Bird Game",
    coverImage: "/covers/talha37-09-flappy-bird-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Flappy Bird Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Retro", "Reflex", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-09-flappy-bird-game/index.html",
  },
  {
    slug: "talha37-10-2048-game",
    title: "2048 Game",
    coverImage: "/covers/talha37-10-2048-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted 2048 Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Arcade"],
    tags: ["Puzzle", "Casual", "Score Attack"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-10-2048-game/index.html",
  },
  {
    slug: "talha37-11-wordle-game",
    title: "Wordle Game",
    coverImage: "/covers/talha37-11-wordle-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Wordle Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Words", "Letters", "Guessing"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-11-wordle-game/index.html",
  },
  {
    slug: "talha37-12-hangman-game",
    title: "Hangman Game",
    coverImage: "/covers/talha37-12-hangman-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Hangman Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Words", "Letters", "Guessing"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-12-hangman-game/index.html",
  },
  {
    slug: "talha37-13-tower-blocks",
    title: "Tower Blocks",
    coverImage: "/covers/talha37-13-tower-blocks.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Tower Blocks implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade", "Skill"],
    tags: ["Skill", "Score Attack", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-13-tower-blocks/index.html",
  },
  {
    slug: "talha37-14-archery-game",
    title: "Archery Game",
    coverImage: "/covers/talha37-14-archery-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Archery Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade", "Skill"],
    tags: ["Skill", "Score Attack", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-14-archery-game/index.html",
  },
  {
    slug: "talha37-15-tic-tac-toe",
    title: "Tic Tac Toe",
    coverImage: "/covers/talha37-15-tic-tac-toe.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Tic Tac Toe implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Arcade"],
    tags: ["Board", "Versus", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-15-tic-tac-toe/index.html",
  },
  {
    slug: "talha37-16-minesweeper-game",
    title: "Minesweeper Game",
    coverImage: "/covers/talha37-16-minesweeper-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Minesweeper Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Grid", "Classic", "Logic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-16-minesweeper-game/index.html",
  },
  {
    slug: "talha37-17-speed-typing-game",
    title: "Speed Typing Game 17",
    coverImage: "/covers/talha37-17-speed-typing-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Speed Typing Game 17 implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Puzzle"],
    tags: ["Keyboard", "Reflex", "Words"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-17-speed-typing-game/index.html",
  },
  {
    slug: "talha37-18-breakout-game",
    title: "Breakout Game",
    coverImage: "/covers/talha37-18-breakout-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Breakout Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Retro", "Reflex", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-18-breakout-game/index.html",
  },
  {
    slug: "talha37-19-ping-pong-game",
    title: "Ping Pong Game",
    coverImage: "/covers/talha37-19-ping-pong-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Ping Pong Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Retro", "Reflex", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-19-ping-pong-game/index.html",
  },
  {
    slug: "talha37-20-tetris-game",
    title: "Tetris Game",
    coverImage: "/covers/talha37-20-tetris-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Tetris Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Arcade"],
    tags: ["Puzzle", "Casual", "Score Attack"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-20-tetris-game/index.html",
  },
  {
    slug: "talha37-21-tilting-maze-game",
    title: "Tilting Maze Game",
    coverImage: "/covers/talha37-21-tilting-maze-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Tilting Maze Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-21-tilting-maze-game/index.html",
  },
  {
    slug: "talha37-22-memory-card-game",
    title: "Memory Card Game",
    coverImage: "/covers/talha37-22-memory-card-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Memory Card Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Arcade"],
    tags: ["Puzzle", "Casual", "Score Attack"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-22-memory-card-game/index.html",
  },
  {
    slug: "talha37-23-type-number-guessing-game",
    title: "Type Number Guessing Game 23",
    coverImage: "/covers/talha37-23-type-number-guessing-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Type Number Guessing Game 23 implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Puzzle"],
    tags: ["Numbers", "Casual", "Quick Play"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-23-type-number-guessing-game/index.html",
  },
  {
    slug: "talha37-24-snake-game",
    title: "Snake Game",
    coverImage: "/covers/talha37-24-snake-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Snake Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Retro", "Reflex", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-24-snake-game/index.html",
  },
  {
    slug: "talha37-25-connect-four-game",
    title: "Connect Four Game",
    coverImage: "/covers/talha37-25-connect-four-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Connect Four Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Board", "Versus", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-25-connect-four-game/index.html",
  },
  {
    slug: "talha37-26-insect-catch-game",
    title: "Insect Catch Game",
    coverImage: "/covers/talha37-26-insect-catch-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Insect Catch Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-26-insect-catch-game/index.html",
  },
  {
    slug: "talha37-27-typing-game",
    title: "Typing Game 27",
    coverImage: "/covers/talha37-27-typing-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Typing Game 27 implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Puzzle"],
    tags: ["Keyboard", "Reflex", "Words"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-27-typing-game/index.html",
  },
  {
    slug: "talha37-28-dice-roll-simulator",
    title: "Dice Roll Simulator",
    coverImage: "/covers/talha37-28-dice-roll-simulator.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Dice Roll Simulator implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-28-dice-roll-simulator/index.html",
  },
  {
    slug: "talha37-29-shape-clicker-game",
    title: "Shape Clicker Game",
    coverImage: "/covers/talha37-29-shape-clicker-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Shape Clicker Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-29-shape-clicker-game/index.html",
  },
  {
    slug: "talha37-30-typing-game",
    title: "Typing Game 30",
    coverImage: "/covers/talha37-30-typing-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Typing Game 30 implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Puzzle"],
    tags: ["Keyboard", "Reflex", "Words"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-30-typing-game/index.html",
  },
  {
    slug: "talha37-31-speak-number-guessing-game",
    title: "Speak Number Guessing Game 31",
    coverImage: "/covers/talha37-31-speak-number-guessing-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Speak Number Guessing Game 31 implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Puzzle"],
    tags: ["Numbers", "Casual", "Quick Play"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-31-speak-number-guessing-game/index.html",
  },
  {
    slug: "talha37-32-fruit-slicer-game",
    title: "Fruit Slicer Game",
    coverImage: "/covers/talha37-32-fruit-slicer-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Fruit Slicer Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Skill", "Score Attack", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-32-fruit-slicer-game/index.html",
  },
  {
    slug: "talha37-33-quiz-game",
    title: "Quiz Game",
    coverImage: "/covers/talha37-33-quiz-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Quiz Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-33-quiz-game/index.html",
  },
  {
    slug: "talha37-34-emoji-catcher-game",
    title: "Emoji Catcher Game",
    coverImage: "/covers/talha37-34-emoji-catcher-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Emoji Catcher Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-34-emoji-catcher-game/index.html",
  },
  {
    slug: "talha37-35-whack-a-mole-game",
    title: "Whack A Mole Game",
    coverImage: "/covers/talha37-35-whack-a-mole-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Whack A Mole Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-35-whack-a-mole-game/index.html",
  },
  {
    slug: "talha37-36-simon-says-game",
    title: "Simon Says Game",
    coverImage: "/covers/talha37-36-simon-says-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Simon Says Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-36-simon-says-game/index.html",
  },
  {
    slug: "talha37-37-sliding-puzzle-game",
    title: "Sliding Puzzle Game",
    coverImage: "/covers/talha37-37-sliding-puzzle-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Sliding Puzzle Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha37-37-sliding-puzzle-game/index.html",
  },
];