import type { Game } from "./games";

export const talhaGames: Game[] = [
  {
    slug: "talha-candy-crush-game",
    title: "Candy Crush Game",
    coverImage: "/covers/talha-candy-crush-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Candy Crush Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Puzzle", "Casual", "Score Attack"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-candy-crush-game/index.html",
  },
  {
    slug: "talha-pac-man-game",
    title: "Pac Man Game",
    coverImage: "/covers/talha-pac-man-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Pac Man Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-pac-man-game/index.html",
  },
  {
    slug: "talha-chess-game",
    title: "Chess Game",
    coverImage: "/covers/talha-chess-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Chess Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Board", "Logic", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-chess-game/index.html",
  },
  {
    slug: "talha-doodle-jump-game",
    title: "Doodle Jump Game",
    coverImage: "/covers/talha-doodle-jump-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Doodle Jump Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-doodle-jump-game/index.html",
  },
  {
    slug: "talha-solitaire-game",
    title: "Solitaire Game",
    coverImage: "/covers/talha-solitaire-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Solitaire Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-solitaire-game/index.html",
  },
  {
    slug: "talha-sudoku-game",
    title: "Sudoku Game",
    coverImage: "/covers/talha-sudoku-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Sudoku Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Numbers", "Logic", "Grid"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-sudoku-game/index.html",
  },
  {
    slug: "talha-crossy-road-game",
    title: "Crossy Road Game",
    coverImage: "/covers/talha-crossy-road-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Crossy Road Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-crossy-road-game/index.html",
  },
  {
    slug: "talha-rock-paper-scissors",
    title: "Rock Paper Scissors",
    coverImage: "/covers/talha-rock-paper-scissors.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Rock Paper Scissors implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-rock-paper-scissors/index.html",
  },
  {
    slug: "talha-flappy-bird-game",
    title: "Flappy Bird Game",
    coverImage: "/covers/talha-flappy-bird-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Flappy Bird Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Retro", "Reflex", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-flappy-bird-game/index.html",
  },
  {
    slug: "talha-2048-game",
    title: "2048 Game",
    coverImage: "/covers/talha-2048-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted 2048 Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Arcade"],
    tags: ["Puzzle", "Casual", "Score Attack"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-2048-game/index.html",
  },
  {
    slug: "talha-wordle-game",
    title: "Wordle Game",
    coverImage: "/covers/talha-wordle-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Wordle Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Words", "Letters", "Guessing"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-wordle-game/index.html",
  },
  {
    slug: "talha-hangman-game",
    title: "Hangman Game",
    coverImage: "/covers/talha-hangman-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Hangman Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Words", "Letters", "Guessing"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-hangman-game/index.html",
  },
  {
    slug: "talha-tower-blocks",
    title: "Tower Blocks",
    coverImage: "/covers/talha-tower-blocks.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Tower Blocks implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade", "Skill"],
    tags: ["Skill", "Score Attack", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-tower-blocks/index.html",
  },
  {
    slug: "talha-archery-game",
    title: "Archery Game",
    coverImage: "/covers/talha-archery-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Archery Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade", "Skill"],
    tags: ["Skill", "Score Attack", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-archery-game/index.html",
  },
  {
    slug: "talha-tic-tac-toe",
    title: "Tic Tac Toe",
    coverImage: "/covers/talha-tic-tac-toe.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Tic Tac Toe implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Arcade"],
    tags: ["Board", "Versus", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-tic-tac-toe/index.html",
  },
  {
    slug: "talha-minesweeper-game",
    title: "Minesweeper Game",
    coverImage: "/covers/talha-minesweeper-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Minesweeper Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Grid", "Classic", "Logic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-minesweeper-game/index.html",
  },
  {
    slug: "talha-speed-typing-game",
    title: "Speed Typing Game",
    coverImage: "/covers/talha-speed-typing-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Speed Typing Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Puzzle"],
    tags: ["Keyboard", "Reflex", "Words"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-speed-typing-game/index.html",
  },
  {
    slug: "talha-breakout-game",
    title: "Breakout Game",
    coverImage: "/covers/talha-breakout-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Breakout Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Retro", "Reflex", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-breakout-game/index.html",
  },
  {
    slug: "talha-ping-pong-game",
    title: "Ping Pong Game",
    coverImage: "/covers/talha-ping-pong-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Ping Pong Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Retro", "Reflex", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-ping-pong-game/index.html",
  },
  {
    slug: "talha-tetris-game",
    title: "Tetris Game",
    coverImage: "/covers/talha-tetris-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Tetris Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Arcade"],
    tags: ["Puzzle", "Casual", "Score Attack"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-tetris-game/index.html",
  },
  {
    slug: "talha-tilting-maze-game",
    title: "Tilting Maze Game",
    coverImage: "/covers/talha-tilting-maze-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Tilting Maze Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-tilting-maze-game/index.html",
  },
  {
    slug: "talha-memory-card-game",
    title: "Memory Card Game",
    coverImage: "/covers/talha-memory-card-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Memory Card Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Arcade"],
    tags: ["Puzzle", "Casual", "Score Attack"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-memory-card-game/index.html",
  },
  {
    slug: "talha-type-number-guessing-game",
    title: "Type Number Guessing Game",
    coverImage: "/covers/talha-type-number-guessing-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Type Number Guessing Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Puzzle"],
    tags: ["Numbers", "Casual", "Quick Play"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-type-number-guessing-game/index.html",
  },
  {
    slug: "talha-snake-game",
    title: "Snake Game",
    coverImage: "/covers/talha-snake-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Snake Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Retro", "Reflex", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-snake-game/index.html",
  },
  {
    slug: "talha-connect-four-game",
    title: "Connect Four Game",
    coverImage: "/covers/talha-connect-four-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Connect Four Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Board", "Versus", "Classic"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-connect-four-game/index.html",
  },
  {
    slug: "talha-insect-catch-game",
    title: "Insect Catch Game",
    coverImage: "/covers/talha-insect-catch-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Insect Catch Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-insect-catch-game/index.html",
  },
  {
    slug: "talha-typing-game",
    title: "Typing Game",
    coverImage: "/covers/talha-typing-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Typing Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Puzzle"],
    tags: ["Keyboard", "Reflex", "Words"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-typing-game/index.html",
  },
  {
    slug: "talha-dice-roll-simulator",
    title: "Dice Roll Simulator",
    coverImage: "/covers/talha-dice-roll-simulator.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Dice Roll Simulator implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-dice-roll-simulator/index.html",
  },
  {
    slug: "talha-shape-clicker-game",
    title: "Shape Clicker Game",
    coverImage: "/covers/talha-shape-clicker-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Shape Clicker Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-shape-clicker-game/index.html",
  },
  {
    slug: "talha-typing-game",
    title: "Typing Game",
    coverImage: "/covers/talha-typing-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Typing Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Puzzle"],
    tags: ["Keyboard", "Reflex", "Words"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-typing-game/index.html",
  },
  {
    slug: "talha-speak-number-guessing-game",
    title: "Speak Number Guessing Game",
    coverImage: "/covers/talha-speak-number-guessing-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Speak Number Guessing Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Casual", "Puzzle"],
    tags: ["Numbers", "Casual", "Quick Play"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-speak-number-guessing-game/index.html",
  },
  {
    slug: "talha-fruit-slicer-game",
    title: "Fruit Slicer Game",
    coverImage: "/covers/talha-fruit-slicer-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Fruit Slicer Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Skill", "Score Attack", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-fruit-slicer-game/index.html",
  },
  {
    slug: "talha-quiz-game",
    title: "Quiz Game",
    coverImage: "/covers/talha-quiz-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Quiz Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-quiz-game/index.html",
  },
  {
    slug: "talha-emoji-catcher-game",
    title: "Emoji Catcher Game",
    coverImage: "/covers/talha-emoji-catcher-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Emoji Catcher Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-emoji-catcher-game/index.html",
  },
  {
    slug: "talha-whack-a-mole-game",
    title: "Whack A Mole Game",
    coverImage: "/covers/talha-whack-a-mole-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Whack A Mole Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-whack-a-mole-game/index.html",
  },
  {
    slug: "talha-simon-says-game",
    title: "Simon Says Game",
    coverImage: "/covers/talha-simon-says-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Simon Says Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Arcade"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-simon-says-game/index.html",
  },
  {
    slug: "talha-sliding-puzzle-game",
    title: "Sliding Puzzle Game",
    coverImage: "/covers/talha-sliding-puzzle-game.svg",
    shortDescription: "Browser game from the HTML, CSS and JavaScript games collection.",
    description: "Self-hosted Sliding Puzzle Game implementation imported from the HTML, CSS and JavaScript games repository.",
    categories: ["Puzzle", "Strategy"],
    tags: ["Browser", "Casual", "Arcade"],
    featured: false,
    mobile: false,
    license: "MIT",
    sourceUrl: "https://github.com/he-is-talha/html-css-javascript-games",
    attribution: "he-is-talha and contributors",
    embedUrl: "/games/talha-sliding-puzzle-game/index.html",
  },
];